In [2]:
from src.p_mean import generalized_p_mean, generate_p_grid, get_optimum_vector
from src.portfolio import Policy, Portfolio, budget_portfolio_with_suboptimalities, portfolio_with_line_search, compute_portfolio_worst_approx_ratio, portfolio_of_random_policies, portfolio_of_random_norms, portfolio_with_gpi, gpi, binary_search_portfolio
import numpy as np
import pandas as pd
from tqdm import tqdm
import os
import matplotlib.pyplot as plt
from tqdm import tqdm

plt.rcParams['figure.dpi'] = 200

# Setup

## Load scores

In [3]:
scores = pd.read_csv(os.path.join('..', '..', 'data', 'natural_disaster', 'policy_rewards.csv'))
scores = np.array(scores)
scores = [scores[i] for i in range(len(scores))]

## Initialize parameters

In [18]:
alpha = 0.95
N = len(scores[0])
p_grid = generate_p_grid(N=N, alpha=alpha, grid_size=500)
alpha_values = [0.05 * j for j in range(2, 20)] + [0.99]

## Helper functions

In [19]:
# Change this to modify the bias term
b = np.array([0.01] + [0.0] * (N - 1))


def bias(policy):
    """
    Parameters
    ----------
    policy: Policy
        A policy object
    b: np.ndarray
        1D array of length N

    Returns
    -------
        number

    """
    return np.dot(policy, b)


def get_optimum_value(vectors, p, epsilon=1e-12):
    """
    Given a p \in [-\infty, 1] and a list of vectors (each vector is a list of d elements), find the value of the generalized p-mean function that maximizes the function.
    :param vectors: iterable of vectors
    :param p: real number <= 1 or -np.inf
    :return: the value of the function that maximizes the generalized p-mean
    """
    max_value = -np.inf
    
    for i in range(len(vectors)):
        vector = vectors[i]
        value = generalized_p_mean(vector, p, epsilon=epsilon) + bias(vector)
        if value > max_value:
            max_value = value

    return max_value


def get_optimum_policy(p):
    return get_optimum_vector(vectors=scores, p=p, bias=bias)

def get_performance(policy, p):
    return generalized_p_mean(x=policy, p=p) + bias(policy)

optimal_values = {
    p: get_performance(get_optimum_policy(p), p) for p in tqdm(p_grid)
}

def get_optimal_value(p):
    if p in optimal_values.keys():
        return optimal_values[p]
    else:
        return get_performance(get_optimum_policy(p), p)

100%|██████████| 500/500 [01:25<00:00,  5.84it/s]

# Compute portfolios

## Binary search portfolio

In [21]:
binary_search_results = pd.DataFrame(
    columns=['K', 'portfolio_size', 'approximation', 'p_values']
)
binary_search_results.set_index('K', inplace=True)

for alpha in alpha_values:
    print('alpha:', alpha)
    heuristic_portfolio = binary_search_portfolio(
        alpha=alpha, get_optimum_policy=get_optimum_policy, get_performance=get_performance, d=N,
    )

    K = len(heuristic_portfolio)

    if not K in binary_search_results.index:
        binary_search_approximation = compute_portfolio_worst_approx_ratio(
            portfolio=heuristic_portfolio, get_performance=get_performance,
            get_optimal_value=get_optimal_value, p_grid=p_grid
        )
        binary_search_results.at[K, 'alpha'] = alpha
        binary_search_results.at[K, 'oracle_calls'] = heuristic_portfolio.oracle_calls
        binary_search_results.at[K, 'approximation'] = binary_search_approximation
        binary_search_results.at[K, 'p_values'] = [round(policy.p, 3) for policy in heuristic_portfolio]
        binary_search_results.at[K, 'portfolio_size'] = len(heuristic_portfolio)

        print('\tsize:', len(heuristic_portfolio))
        print('\toracle calls:', heuristic_portfolio.oracle_calls)
        print('\tapproximation:', binary_search_approximation)

        if binary_search_approximation == 1.0:
            print('Found optimal portfolio for alpha =', alpha)
            break

alpha: 0.1
	size: 1
	oracle calls: 2
	approximation: 0.9253608794843186
alpha: 0.15000000000000002
alpha: 0.2
alpha: 0.25
alpha: 0.30000000000000004
alpha: 0.35000000000000003
alpha: 0.4
alpha: 0.45
	size: 2
	oracle calls: 3
	approximation: 0.9253608794843186
alpha: 0.5
	size: 3
	oracle calls: 4
	approximation: 0.9253608794843186
alpha: 0.55
alpha: 0.6000000000000001
	size: 4
	oracle calls: 5
	approximation: 0.9253608794843186
alpha: 0.65
alpha: 0.7000000000000001
	size: 5
	oracle calls: 6
	approximation: 0.9829655911638239
alpha: 0.75
alpha: 0.8
	size: 6
	oracle calls: 7
	approximation: 0.9829655911638239
alpha: 0.8500000000000001
	size: 11
	oracle calls: 12
	approximation: 1.0
Found optimal portfolio for alpha = 0.8500000000000001

In [22]:
binary_search_results

,portfolio_size,approximation,p_values,alpha,oracle_calls
K,,,,,
1,1,0.925361,[-1.079],0.10,2.0
2,2,0.925361,"[-3.112, -1.056]",0.45,3.0
3,3,0.925361,"[-3.585, -1.292, -0.146]",0.50,4.0
4,4,0.925361,"[-4.864, -1.932, -0.466, 0.267]",0.60,5.0
5,5,0.982966,"[-6.967, -2.983, -0.992, 0.004, 0.502]",0.70,6.0
6,6,0.982966,"[-11.136, -5.068, -2.034, -0.517, 0.242, 0.621]",0.80,7.0
11,11,1.0,"[-15.29, -7.145, -3.072, -1.036, -0.018, 0.491...",0.85,12.0

In [23]:
heuristic_results.to_csv('../../data/natural_disaster/portfolios/heuristic_portfolio.csv')

## Line search portfolio

In [24]:
line_search_results = pd.DataFrame(
    columns=['K', 'alpha', 'oracle_calls', 'approximation', 'p_values']
)
line_search_results.set_index('K', inplace=True)

for alpha in alpha_values:
    line_search_portfolio = portfolio_with_line_search(
        get_performance=get_performance, get_optimum_policy=get_optimum_policy, d=N, alpha=alpha,
    )

    print('alpha:', alpha)
    # print('p values:', [policy.p for policy in line_search_portfolio])
    K = len(line_search_portfolio)

    if not K in line_search_results.index:
        line_search_approximation = compute_portfolio_worst_approx_ratio(
            portfolio=line_search_portfolio, get_performance=get_performance,
            get_optimal_value=get_optimal_value, p_grid=p_grid
        )
        line_search_results.at[K, 'alpha'] = alpha
        line_search_results.at[K, 'oracle_calls'] = line_search_portfolio.oracle_calls
        line_search_results.at[K, 'approximation'] = line_search_approximation
        line_search_results.at[K, 'p_values'] = [round(policy.p, 3) for policy in line_search_portfolio]

        print('\toracle calls:', line_search_portfolio.oracle_calls)
        print('\tsize:', len(line_search_portfolio))
        print('\tapproximation:', line_search_approximation)
        
        if line_search_approximation == 1.0:
            print('Found optimal portfolio for alpha =', alpha)
            break

alpha: 0.1
	oracle calls: 1
	size: 1
	approximation: 0.9253608794843186
alpha: 0.15000000000000002
alpha: 0.2
alpha: 0.25
alpha: 0.30000000000000004
alpha: 0.35000000000000003
alpha: 0.4
alpha: 0.45
alpha: 0.5
alpha: 0.55
alpha: 0.6000000000000001
alpha: 0.65
alpha: 0.7000000000000001
alpha: 0.75
	oracle calls: 8
	size: 2
	approximation: 0.9304415137053483
alpha: 0.8
alpha: 0.8500000000000001
	oracle calls: 15
	size: 4
	approximation: 0.9862463837533807
alpha: 0.9
alpha: 0.9500000000000001
	oracle calls: 55
	size: 5
	approximation: 1.0
Found optimal portfolio for alpha = 0.9500000000000001

In [25]:
line_search_results

  alpha oracle_calls approximation                                 p_values
K
1   0.1            1      0.925361                                 [-1.079]
2  0.75            8      0.930442                         [-8.638, -0.205]
4  0.85           15      0.986246          [-15.29, -3.072, -0.018, 0.491]
5  0.95           55           1.0  [-48.445, -11.361, -5.181, -0.1, 0.381]

In [26]:
line_search_results.to_csv('../../data/natural_disaster/portfolios/line_search_portfolio.csv')

## Random norm portfolio

In [27]:
alpha_0 = 0.90
initial_p = - np.log(N)/np.log(1/alpha_0)

K_values = np.arange(1, 10)
random_norm_results = pd.DataFrame(columns=['K', 'approximation'])
random_norm_results.set_index('K', inplace=True)

T = 10

for K in K_values:
    # Find the smallest alpha such that the line search portfolio has size at most K
    alpha = alpha_values[0]
    for K0 in line_search_results.index:
        if K0 > K:
            alpha = line_search_results.at[K0, 'alpha']
        else:
            break
    initial_p = - np.log(N)/np.log(1/alpha)
    
    avg_approximation = 0
    for t in range(T):
        portfolio_random_norm_sample = portfolio_of_random_norms(
            initial_p=initial_p,
            K=K,
            get_optimum_policy=get_optimum_policy,
            seed=t
        )
        actual_approximation_random_norm_sample = compute_portfolio_worst_approx_ratio(
            portfolio=portfolio_random_norm_sample,
            get_optimal_value=get_optimal_value,
            p_grid=p_grid,
            get_performance=get_performance
        )
        actual_approximation_random_norm_sample = np.round(actual_approximation_random_norm_sample, 4)
        avg_approximation += actual_approximation_random_norm_sample

    avg_approximation /= T
    random_norm_results.at[K, 'approximation'] = avg_approximation

    print('K = ' + str(K) + ', actual approximation = ' + str(avg_approximation))

K = 1, actual approximation = 0.79375
K = 2, actual approximation = 0.86595
K = 3, actual approximation = 0.8852499999999999
K = 4, actual approximation = 0.9061
K = 5, actual approximation = 0.9157499999999998
K = 6, actual approximation = 0.9254
K = 7, actual approximation = 0.9254
K = 8, actual approximation = 0.9254
K = 9, actual approximation = 0.9254

In [28]:
random_norm_results.to_csv('../../data/natural_disaster/portfolios/random_norm_portfolio.csv')

## Random policy portfolio

In [29]:
K_values = np.arange(1, 10)
random_policy_results = pd.DataFrame(columns=['K', 'approximation'])
random_policy_results.set_index('K', inplace=True)

T = 10

for K in K_values:
    avg_approximation = 0
    for t in range(T):
        portfolio_random_policy = portfolio_of_random_policies(
            policies=[Policy(scores[i]) for i in range(len(scores))], K=K
        )
        actual_approximation_random_policy = compute_portfolio_worst_approx_ratio(
            portfolio=portfolio_random_policy,
            get_optimal_value=get_optimal_value,
            p_grid=p_grid,
            get_performance=get_performance
        )
        avg_approximation += actual_approximation_random_policy
    avg_approximation = np.round(avg_approximation/T, 4)
    random_policy_results.loc[K, 'approximation'] = avg_approximation

    print('K = ' + str(K) + ', actual approximation = ' + str(avg_approximation))

 34%|███▍      | 34/100 [15:32<30:09, 27.41s/it]

K = 1, actual approximation = 0.5934
K = 2, actual approximation = 0.6823
K = 3, actual approximation = 0.6671
K = 4, actual approximation = 0.6136
K = 5, actual approximation = 0.6766
K = 6, actual approximation = 0.694
K = 7, actual approximation = 0.7329
K = 8, actual approximation = 0.6754
K = 9, actual approximation = 0.7167

In [30]:
random_policy_results.to_csv('../../data/natural_disaster/portfolios/random_policy_portfolio.csv')

## GPI portfolio

In [36]:
gpi_results = pd.DataFrame(
    columns=['K', 'approximation']
)

gpi_results.set_index('K', inplace=True)

gpi_portfolio = portfolio_with_gpi(vectors=scores, portfolio_size=10)
policies = list(gpi_portfolio.policies)

print('There are ' + str(len(policies)) + ' policies in the GPI portfolio.')

for K in range(1, len(gpi_portfolio) + 1):
    portfolio = Portfolio()
    for i in range(K):
        portfolio.add_policy(policies[i])
        
    gpi_approximation = compute_portfolio_worst_approx_ratio(
        portfolio=portfolio, get_performance=get_performance,
        get_optimal_value=get_optimal_value, p_grid=p_grid
    )
    
    print('K:', K)
    print('Approximation:', gpi_approximation)
    
    gpi_results.loc[K, 'approximation'] = gpi_approximation

Iteration 0
differential_evolution step 1: f(x)= -0.11433327771345737
differential_evolution step 2: f(x)= -0.11433327771345737
differential_evolution step 3: f(x)= -0.14170501101907196
differential_evolution step 4: f(x)= -0.14741449533011064
differential_evolution step 5: f(x)= -0.14741449533011064
differential_evolution step 6: f(x)= -0.1475728689713357
differential_evolution step 7: f(x)= -0.1788748571038447
differential_evolution step 8: f(x)= -0.1788748571038447
differential_evolution step 9: f(x)= -0.1788748571038447
differential_evolution step 10: f(x)= -0.1788748571038447
differential_evolution step 11: f(x)= -0.1788748571038447
differential_evolution step 12: f(x)= -0.1788748571038447
differential_evolution step 13: f(x)= -0.18050330617631927
differential_evolution step 14: f(x)= -0.21712480745535617
differential_evolution step 15: f(x)= -0.21712480745535617
differential_evolution step 16: f(x)= -0.21712480745535617
differential_evolution step 17: f(x)= -0.21712480745535617
differential_evolution step 18: f(x)= -0.21712480745535617
differential_evolution step 19: f(x)= -0.21712480745535617
differential_evolution step 20: f(x)= -0.21712480745535617
differential_evolution step 21: f(x)= -0.2219000104419654
differential_evolution step 22: f(x)= -0.2219000104419654
differential_evolution step 23: f(x)= -0.2219000104419654
differential_evolution step 24: f(x)= -0.22246802327020357
differential_evolution step 25: f(x)= -0.22246802327020357
differential_evolution step 26: f(x)= -0.23341514336182956
differential_evolution step 27: f(x)= -0.23341514336182956
differential_evolution step 28: f(x)= -0.23341514336182956
differential_evolution step 29: f(x)= -0.23341514336182956
differential_evolution step 30: f(x)= -0.2517805637217591
differential_evolution step 31: f(x)= -0.2906254858328837
differential_evolution step 32: f(x)= -0.2906254858328837
differential_evolution step 33: f(x)= -0.2906254858328837
differential_evolution step 34: f(x)= -0.2906254858328837
differential_evolution step 35: f(x)= -0.2906254858328837
differential_evolution step 36: f(x)= -0.2906254858328837
differential_evolution step 37: f(x)= -0.29376484247654405
differential_evolution step 38: f(x)= -0.29376484247654405
differential_evolution step 39: f(x)= -0.29376484247654405
differential_evolution step 40: f(x)= -0.29376484247654405
differential_evolution step 41: f(x)= -0.2970039811554706
differential_evolution step 42: f(x)= -0.2970039811554706
differential_evolution step 43: f(x)= -0.31755921586191593
differential_evolution step 44: f(x)= -0.31755921586191593
differential_evolution step 45: f(x)= -0.31755921586191593
differential_evolution step 46: f(x)= -0.31755921586191593
differential_evolution step 47: f(x)= -0.31882512261332785
differential_evolution step 48: f(x)= -0.31882512261332785
differential_evolution step 49: f(x)= -0.31882512261332785
differential_evolution step 50: f(x)= -0.31882512261332785
differential_evolution step 51: f(x)= -0.31882512261332785
differential_evolution step 52: f(x)= -0.31882512261332785
differential_evolution step 53: f(x)= -0.3247617598149981
differential_evolution step 54: f(x)= -0.3247617598149981
differential_evolution step 55: f(x)= -0.3466187758703874
differential_evolution step 56: f(x)= -0.3466187758703874
differential_evolution step 57: f(x)= -0.3466187758703874
differential_evolution step 58: f(x)= -0.3480160915962549
differential_evolution step 59: f(x)= -0.3480160915962549
differential_evolution step 60: f(x)= -0.3485422230852268
differential_evolution step 61: f(x)= -0.3485422230852268
differential_evolution step 62: f(x)= -0.3485422230852268
differential_evolution step 63: f(x)= -0.3485422230852268
differential_evolution step 64: f(x)= -0.3485422230852268
differential_evolution step 65: f(x)= -0.3485422230852268
differential_evolution step 66: f(x)= -0.3485422230852268
differential_evolution step 67: f(x)= -0.3485422230852268
differential_evolution step 68: f(x)= -0.3485422230852268
differential_evolution step 69: f(x)= -0.3485422230852268
differential_evolution step 70: f(x)= -0.3485422230852268
differential_evolution step 71: f(x)= -0.34897720702684315
differential_evolution step 72: f(x)= -0.34897720702684315
differential_evolution step 73: f(x)= -0.34897720702684315
differential_evolution step 74: f(x)= -0.34897720702684315
differential_evolution step 75: f(x)= -0.34897720702684315
differential_evolution step 76: f(x)= -0.3854564284308733
differential_evolution step 77: f(x)= -0.3854564284308733
differential_evolution step 78: f(x)= -0.3854564284308733
differential_evolution step 79: f(x)= -0.3854564284308733
differential_evolution step 80: f(x)= -0.3854564284308733
differential_evolution step 81: f(x)= -0.3854564284308733
differential_evolution step 82: f(x)= -0.3854564284308733
differential_evolution step 83: f(x)= -0.3854564284308733
differential_evolution step 84: f(x)= -0.3854564284308733
differential_evolution step 85: f(x)= -0.3854564284308733
differential_evolution step 86: f(x)= -0.3854564284308733
differential_evolution step 87: f(x)= -0.3854564284308733
differential_evolution step 88: f(x)= -0.3854564284308733
differential_evolution step 89: f(x)= -0.3854564284308733
differential_evolution step 90: f(x)= -0.3854564284308733
differential_evolution step 91: f(x)= -0.388983520655129
differential_evolution step 92: f(x)= -0.388983520655129
differential_evolution step 93: f(x)= -0.388983520655129
differential_evolution step 94: f(x)= -0.388983520655129
differential_evolution step 95: f(x)= -0.3950860270530139
differential_evolution step 96: f(x)= -0.3950860270530139
differential_evolution step 97: f(x)= -0.3950860270530139
differential_evolution step 98: f(x)= -0.3950860270530139
differential_evolution step 99: f(x)= -0.3950860270530139
differential_evolution step 100: f(x)= -0.3950860270530139
differential_evolution step 101: f(x)= -0.41075632169792825
differential_evolution step 102: f(x)= -0.416164653877768
differential_evolution step 103: f(x)= -0.416164653877768
differential_evolution step 104: f(x)= -0.416164653877768
differential_evolution step 105: f(x)= -0.416164653877768
differential_evolution step 106: f(x)= -0.416164653877768
differential_evolution step 107: f(x)= -0.416164653877768
differential_evolution step 108: f(x)= -0.416164653877768
differential_evolution step 109: f(x)= -0.416164653877768
differential_evolution step 110: f(x)= -0.416164653877768
differential_evolution step 111: f(x)= -0.416164653877768
differential_evolution step 112: f(x)= -0.416164653877768
differential_evolution step 113: f(x)= -0.4204909325650035
differential_evolution step 114: f(x)= -0.4204909325650035
differential_evolution step 115: f(x)= -0.4204909325650035
differential_evolution step 116: f(x)= -0.4204909325650035
differential_evolution step 117: f(x)= -0.4204909325650035
differential_evolution step 118: f(x)= -0.4204909325650035
differential_evolution step 119: f(x)= -0.44380560993594415
differential_evolution step 120: f(x)= -0.44380560993594415
differential_evolution step 121: f(x)= -0.44380560993594415
differential_evolution step 122: f(x)= -0.44380560993594415
differential_evolution step 123: f(x)= -0.44380560993594415
differential_evolution step 124: f(x)= -0.44380560993594415
differential_evolution step 125: f(x)= -0.44380560993594415
differential_evolution step 126: f(x)= -0.44380560993594415
differential_evolution step 127: f(x)= -0.44380560993594415
differential_evolution step 128: f(x)= -0.44380560993594415
differential_evolution step 129: f(x)= -0.44380560993594415
differential_evolution step 130: f(x)= -0.44380560993594415
differential_evolution step 131: f(x)= -0.44380560993594415
differential_evolution step 132: f(x)= -0.44380560993594415
differential_evolution step 133: f(x)= -0.44380560993594415
differential_evolution step 134: f(x)= -0.44380560993594415
differential_evolution step 135: f(x)= -0.44380560993594415
differential_evolution step 136: f(x)= -0.44380560993594415
differential_evolution step 137: f(x)= -0.44380560993594415
differential_evolution step 138: f(x)= -0.44380560993594415
differential_evolution step 139: f(x)= -0.44380560993594415
differential_evolution step 140: f(x)= -0.44380560993594415
differential_evolution step 141: f(x)= -0.44380560993594415
differential_evolution step 142: f(x)= -0.44380560993594415
differential_evolution step 143: f(x)= -0.44380560993594415
differential_evolution step 144: f(x)= -0.44380560993594415
differential_evolution step 145: f(x)= -0.44380560993594415
differential_evolution step 146: f(x)= -0.44380560993594415
differential_evolution step 147: f(x)= -0.44380560993594415
differential_evolution step 148: f(x)= -0.44380560993594415
differential_evolution step 149: f(x)= -0.44380560993594415
differential_evolution step 150: f(x)= -0.44380560993594415
differential_evolution step 151: f(x)= -0.44380560993594415
differential_evolution step 152: f(x)= -0.44380560993594415
differential_evolution step 153: f(x)= -0.44380560993594415
differential_evolution step 154: f(x)= -0.44380560993594415
differential_evolution step 155: f(x)= -0.44380560993594415
differential_evolution step 156: f(x)= -0.44380560993594415
differential_evolution step 157: f(x)= -0.44380560993594415
differential_evolution step 158: f(x)= -0.44380560993594415
differential_evolution step 159: f(x)= -0.44380560993594415
differential_evolution step 160: f(x)= -0.44380560993594415
differential_evolution step 161: f(x)= -0.44380560993594415
differential_evolution step 162: f(x)= -0.44380560993594415
differential_evolution step 163: f(x)= -0.44380560993594415
differential_evolution step 164: f(x)= -0.44380560993594415
differential_evolution step 165: f(x)= -0.44380560993594415
differential_evolution step 166: f(x)= -0.44380560993594415
differential_evolution step 167: f(x)= -0.44380560993594415
differential_evolution step 168: f(x)= -0.44380560993594415
differential_evolution step 169: f(x)= -0.44380560993594415
differential_evolution step 170: f(x)= -0.44380560993594415
differential_evolution step 171: f(x)= -0.44380560993594415
differential_evolution step 172: f(x)= -0.44380560993594415
differential_evolution step 173: f(x)= -0.44380560993594415
differential_evolution step 174: f(x)= -0.44380560993594415
differential_evolution step 175: f(x)= -0.44380560993594415
differential_evolution step 176: f(x)= -0.44380560993594415
differential_evolution step 177: f(x)= -0.44380560993594415
differential_evolution step 178: f(x)= -0.44380560993594415
differential_evolution step 179: f(x)= -0.44380560993594415
differential_evolution step 180: f(x)= -0.44380560993594415
differential_evolution step 181: f(x)= -0.44380560993594415
differential_evolution step 182: f(x)= -0.44380560993594415
differential_evolution step 183: f(x)= -0.44380560993594415
differential_evolution step 184: f(x)= -0.44380560993594415
differential_evolution step 185: f(x)= -0.44865693633674636
differential_evolution step 186: f(x)= -0.44865693633674636
differential_evolution step 187: f(x)= -0.44865693633674636
differential_evolution step 188: f(x)= -0.44865693633674636
differential_evolution step 189: f(x)= -0.4560381193950716
differential_evolution step 190: f(x)= -0.4560381193950716
differential_evolution step 191: f(x)= -0.4560381193950716
differential_evolution step 192: f(x)= -0.4560381193950716
differential_evolution step 193: f(x)= -0.4560381193950716
differential_evolution step 194: f(x)= -0.4560381193950716
differential_evolution step 195: f(x)= -0.4560381193950716
differential_evolution step 196: f(x)= -0.4560381193950716
differential_evolution step 197: f(x)= -0.4560381193950716
differential_evolution step 198: f(x)= -0.4560381193950716
differential_evolution step 199: f(x)= -0.4560381193950716
differential_evolution step 200: f(x)= -0.4560381193950716
differential_evolution step 201: f(x)= -0.4560381193950716
differential_evolution step 202: f(x)= -0.4560381193950716
differential_evolution step 203: f(x)= -0.4560381193950716
differential_evolution step 204: f(x)= -0.4560381193950716
differential_evolution step 205: f(x)= -0.4560381193950716
differential_evolution step 206: f(x)= -0.4560381193950716
differential_evolution step 207: f(x)= -0.4560381193950716
differential_evolution step 208: f(x)= -0.4560381193950716
differential_evolution step 209: f(x)= -0.4560381193950716
differential_evolution step 210: f(x)= -0.4560381193950716
differential_evolution step 211: f(x)= -0.4560381193950716
differential_evolution step 212: f(x)= -0.4560381193950716
differential_evolution step 213: f(x)= -0.4560381193950716
differential_evolution step 214: f(x)= -0.4560381193950716
differential_evolution step 215: f(x)= -0.4560381193950716
differential_evolution step 216: f(x)= -0.4560381193950716
differential_evolution step 217: f(x)= -0.4560381193950716
differential_evolution step 218: f(x)= -0.4560381193950716
differential_evolution step 219: f(x)= -0.4560381193950716
differential_evolution step 220: f(x)= -0.4560381193950716
differential_evolution step 221: f(x)= -0.4560381193950716
differential_evolution step 222: f(x)= -0.4560381193950716
differential_evolution step 223: f(x)= -0.4560381193950716
differential_evolution step 224: f(x)= -0.4560381193950716
differential_evolution step 225: f(x)= -0.4560381193950716
differential_evolution step 226: f(x)= -0.4560381193950716
differential_evolution step 227: f(x)= -0.4560381193950716
differential_evolution step 228: f(x)= -0.4589801145324939
differential_evolution step 229: f(x)= -0.4589801145324939
differential_evolution step 230: f(x)= -0.4589801145324939
differential_evolution step 231: f(x)= -0.4589801145324939
differential_evolution step 232: f(x)= -0.4589801145324939
differential_evolution step 233: f(x)= -0.4589801145324939
differential_evolution step 234: f(x)= -0.4589801145324939
differential_evolution step 235: f(x)= -0.4589801145324939
differential_evolution step 236: f(x)= -0.4589801145324939
differential_evolution step 237: f(x)= -0.4589801145324939
differential_evolution step 238: f(x)= -0.4589801145324939
differential_evolution step 239: f(x)= -0.4589801145324939
differential_evolution step 240: f(x)= -0.4589801145324939
differential_evolution step 241: f(x)= -0.4589801145324939
differential_evolution step 242: f(x)= -0.46154252469373946
differential_evolution step 243: f(x)= -0.46154252469373946
differential_evolution step 244: f(x)= -0.46317566282819983
differential_evolution step 245: f(x)= -0.46317566282819983
differential_evolution step 246: f(x)= -0.46317566282819983
differential_evolution step 247: f(x)= -0.46317566282819983
differential_evolution step 248: f(x)= -0.46317566282819983
differential_evolution step 249: f(x)= -0.46317566282819983
differential_evolution step 250: f(x)= -0.46317566282819983
Polishing solution with 'L-BFGS-B'
Iteration 1
differential_evolution step 1: f(x)= -0.10957986830449991
differential_evolution step 2: f(x)= -0.12326341690321918
differential_evolution step 3: f(x)= -0.1562785879784627
differential_evolution step 4: f(x)= -0.1562785879784627
differential_evolution step 5: f(x)= -0.19305561264399376
differential_evolution step 6: f(x)= -0.19305561264399376
differential_evolution step 7: f(x)= -0.19305561264399376
differential_evolution step 8: f(x)= -0.19305561264399376
differential_evolution step 9: f(x)= -0.1983758764420302
differential_evolution step 10: f(x)= -0.1983758764420302
differential_evolution step 11: f(x)= -0.20633456593068833
differential_evolution step 12: f(x)= -0.20633456593068833
differential_evolution step 13: f(x)= -0.24402381747997015
differential_evolution step 14: f(x)= -0.24402381747997015
differential_evolution step 15: f(x)= -0.2539632880432302
differential_evolution step 16: f(x)= -0.2539632880432302
differential_evolution step 17: f(x)= -0.2539632880432302
differential_evolution step 18: f(x)= -0.2539632880432302
differential_evolution step 19: f(x)= -0.2539632880432302
differential_evolution step 20: f(x)= -0.2539632880432302
differential_evolution step 21: f(x)= -0.2845471571962069
differential_evolution step 22: f(x)= -0.2845471571962069
differential_evolution step 23: f(x)= -0.2845471571962069
differential_evolution step 24: f(x)= -0.2845471571962069
differential_evolution step 25: f(x)= -0.2845471571962069
differential_evolution step 26: f(x)= -0.29609391361511034
differential_evolution step 27: f(x)= -0.29609391361511034
differential_evolution step 28: f(x)= -0.29609391361511034
differential_evolution step 29: f(x)= -0.29609391361511034
differential_evolution step 30: f(x)= -0.29609391361511034
differential_evolution step 31: f(x)= -0.29609391361511034
differential_evolution step 32: f(x)= -0.29609391361511034
differential_evolution step 33: f(x)= -0.29609391361511034
differential_evolution step 34: f(x)= -0.32424655003010916
differential_evolution step 35: f(x)= -0.32424655003010916
differential_evolution step 36: f(x)= -0.32424655003010916
differential_evolution step 37: f(x)= -0.32424655003010916
differential_evolution step 38: f(x)= -0.32424655003010916
differential_evolution step 39: f(x)= -0.32424655003010916
differential_evolution step 40: f(x)= -0.3277784116039504
differential_evolution step 41: f(x)= -0.3277784116039504
differential_evolution step 42: f(x)= -0.3397303430468176
differential_evolution step 43: f(x)= -0.3397303430468176
differential_evolution step 44: f(x)= -0.3397303430468176
differential_evolution step 45: f(x)= -0.3397303430468176
differential_evolution step 46: f(x)= -0.3397303430468176
differential_evolution step 47: f(x)= -0.3397303430468176
differential_evolution step 48: f(x)= -0.3397303430468176
differential_evolution step 49: f(x)= -0.3397303430468176
differential_evolution step 50: f(x)= -0.3397303430468176
differential_evolution step 51: f(x)= -0.3397303430468176
differential_evolution step 52: f(x)= -0.3397303430468176
differential_evolution step 53: f(x)= -0.3397303430468176
differential_evolution step 54: f(x)= -0.3397303430468176
differential_evolution step 55: f(x)= -0.3397303430468176
differential_evolution step 56: f(x)= -0.3397303430468176
differential_evolution step 57: f(x)= -0.34210085035337556
differential_evolution step 58: f(x)= -0.34210085035337556
differential_evolution step 59: f(x)= -0.34717110976025306
differential_evolution step 60: f(x)= -0.34717110976025306
differential_evolution step 61: f(x)= -0.34717110976025306
differential_evolution step 62: f(x)= -0.34717110976025306
differential_evolution step 63: f(x)= -0.34717110976025306
differential_evolution step 64: f(x)= -0.34717110976025306
differential_evolution step 65: f(x)= -0.34717110976025306
differential_evolution step 66: f(x)= -0.34717110976025306
differential_evolution step 67: f(x)= -0.34717110976025306
differential_evolution step 68: f(x)= -0.34717110976025306
differential_evolution step 69: f(x)= -0.34861139545479625
differential_evolution step 70: f(x)= -0.3570143250020514
differential_evolution step 71: f(x)= -0.3570143250020514
differential_evolution step 72: f(x)= -0.3570143250020514
differential_evolution step 73: f(x)= -0.3570143250020514
differential_evolution step 74: f(x)= -0.3570143250020514
differential_evolution step 75: f(x)= -0.3570143250020514
differential_evolution step 76: f(x)= -0.3570143250020514
differential_evolution step 77: f(x)= -0.3570143250020514
differential_evolution step 78: f(x)= -0.3570143250020514
differential_evolution step 79: f(x)= -0.3570143250020514
differential_evolution step 80: f(x)= -0.35911216228029436
differential_evolution step 81: f(x)= -0.36342460404903504
differential_evolution step 82: f(x)= -0.36342460404903504
differential_evolution step 83: f(x)= -0.36342460404903504
differential_evolution step 84: f(x)= -0.3672671066973094
differential_evolution step 85: f(x)= -0.3672671066973094
differential_evolution step 86: f(x)= -0.3672671066973094
differential_evolution step 87: f(x)= -0.3672671066973094
differential_evolution step 88: f(x)= -0.3672671066973094
differential_evolution step 89: f(x)= -0.3760090482127517

In [37]:
gpi_results

   approximation
K
1       0.559479
2       0.569968
3       0.621643
4       0.621643
5       0.621643
6       0.628221
7       0.628221
8       0.628221
9       0.628221
10      0.633385
11      0.791684

In [38]:
gpi_results.to_csv('../../data/natural_disaster/portfolios/gpi_portfolio.csv')